### ISSUE TITLE
Design ranking algorithm for restaurant scoring

### ISSUE THREAD

**Issue by aeksco** [InspectorRestaurant/ir_web_api#12]
We need to assign a weighted single-number score to each restaurant to "rank" its cleanliness.

I'm thinking it will be a function of the number of inspections, the number of infractions per inspection, the time that's passed since each inspection, and whether or not the infractions were corrected in subsequent inspections.

**Comment by Dmariedwards** [comment]
Handled in the front-end. Scores/grades calculated for each inspection. Critical violations weigh heavier than general violations. Following rubic: 
A: [0,13]
B: [14,27]
C: [28,41]
D: [42, Inf)
